### ISSUE TITLE
can't detect POSIX shell

### ISSUE THREAD

**Issue by asgh** [Zirias/xmoji#2]
```
> make

*** No POSIX shell could be detected while not building on Windows

The zimk build system needs a POSIX compliant shell. Detection of the shell
can be overridden by passing variables to make:

HOSTSH:  Path to the POSIX shell on the build system
         Defaults to the value of SH when not cross-building
SH:      Path to the POSIX shell on the target system

If you know your system has a POSIX shell available, pass its full path in
one of these variables, e.g.

    make SH=/bin/sh

for the most commonly used path.

zimk/lib/platform.mk:73: *** zimk only works with a POSIX shell or Windows CMD.EXE.  Stop.
Exit 2

> make SH=/bin/sh
GNUmakefile:25: *** unterminated call to function 'shell': missing ')'.  Stop.
Exit 2

```

I'm on an old version of Debian, and yes sh is at /bin/sh

I can't tell if this is a xmoji issue or a zimk issue.

**Comment by Zirias** [comment]
Not being able to find the POSIX shell means your old Debian is not fully POSIX compliant (maybe the `getconf` utility is missing, maybe it gives wrong results), but that's unrelated here and passing `SH` works around it.

The second error is probably an issue with some older GNU-make version. Unfortunately I don't know what exactly it coughs on. As a shot in the dark, could you try this patch please:

```
--- a/GNUmakefile
+++ b/GNUmakefile
@@ -22,14 +22,12 @@ DISTCLEANDIRS=              tools/bin
 
 NODIST=                        poser/zimk
 
-HAVE_KQUEUE=           $(shell echo '#include <sys/event.h>\n'\
-                       'int (*f)(void) = kqueue;' | \
-                       $(or $(CC),cc) -xc -c -o/dev/null - 2>/dev/null \
-                       && echo 1)
-HAVE_INOTIFY=          $(shell echo '#include <sys/inotify.h>\n'\
-                       'int (*f)(void) = inotify_init;' | \
-                       $(or $(CC),cc) -xc -c -o/dev/null - 2>/dev/null \
-                       && echo 1)
+define checkfunc
+$(shell echo "#include <$1>\nint (*f)(void) = $2;" | \
+       $(or $(CC),cc) -xc -c -o/dev/null - 2>/dev/null && echo 1)
+endef
+HAVE_KQUEUE=           $(call checkfunc,sys/event.h,kqueue)
+HAVE_INOTIFY=          $(call checkfunc,sys/inotify.h,inotify_init)
 BOOLCONFVARS_OFF+=     $(if $(HAVE_KQUEUE),,WITH_KQUEUE) \
                        $(if $(HAVE_INOTIFY),,WITH_INOTIFY)
 BOOLCONFVARS_ON+=      $(if $(HAVE_KQUEUE),WITH_KQUEUE,) \
```

**Comment by asgh** [comment]
(The patch had tabs vs space mangled, but I managed.)

I do have getconf, and it returns tons of stuff - any particular variable I should check for? This is a very standard Debian, other than being old, it's pretty unlikely it's not POSIX compliant.

Anyway as for the patch:

```
> make WITH_SVG=of SH=/bin/sh HOSTSH=/bin/sh
zimk/lib/config.mk:40: *** bool flag "of" not in [0,no,false,off,1,yes,true,on].  Stop.
Exit 2
```

**Comment by Zirias** [comment]
zimk uses `_POSIX_SHELL` (should return `1` if the system has a POSIX shell) and `PATH` (should return the path where POSIX utilities are found).

Your latest error is a typo here: `WITH_SVG=of` ... it's spelled `off`.

**Comment by asgh** [comment]
My getconf returns the same thing:

```
> getconf _POSIX_SHELL
1
> getconf PATH
/bin:/usr/bin
```

Really sorry about the of vs off!!!

It still won't build, but that's because of missing dependencies, so I'll have to fix that and get back to it.

**Comment by Zirias** [comment]
Then I suppose there's another issue with some older GNU make version ... which one do you have? Maybe I can obtain it to do some debugging.

**Comment by asgh** [comment]
```
> make --version
GNU Make 4.1
Built for i686-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

**Comment by asgh** [comment]
I know it's quite old, I'm actually in the middle of upgrading, so it will be version 4.2 soon. If there's some debugging test you want me to run let me know.

**Comment by Zirias** [comment]
It's 10 years old, I have version 4.4.1 installed here ;) Anyways, confirmed failure to detect the POSIX shell is related to the old GNU make version, I can reproduce it with gmake 4.1 here as well.

**Comment by asgh** [comment]
I have since upgraded Debian which includes the only slightly less ancient version of make 4.2.1 which doesn't have the same error.

I installed the build deps, and got an error which I'll post as a separate issue. Hopefully that error is not because the library I have is too old :)
