### ISSUE TITLE
If LC_TIME is set differently than LC_*, then xmoji fails to start

### ISSUE THREAD

**Issue by ndegruchy** [Zirias/xmoji#7]
I have my locale set as follows:

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME=C
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
When I run xmoji from the command-line after building it, I get the following message:

```
[WARN ]  Configured locale doesn't use UTF-8 encoding, trying `LC_CTYPE=en_US.UTF-8' instead
[ERROR]  Couldn't set locale
```

I can get it to run if I prefix it with a local variable setting `LC_TIME`, like so:

```shell
LC_TIME=en_US.UTF-8 xmoji
```

Seems odd that it would fail with the only thing being the date/time locale being different. Is this by design, or is it a bug?

**Comment by Zirias** [comment]
It's very likely a bug. It *should* look at `LC_CTYPE` only, but maybe I can't rely on the format returned by `setlocale()` for `LC_ALL` ... on which OS did you test that? And just to be sure, did you test with the latest code from the master branch?

**Comment by ndegruchy** [comment]
I am using Debian Stable:

```
cat /etc/debian_version
12.6
```

I did a `git pull --recurse-submodules` just this morning when I tried clicking on the `.desktop` icon. Git reports that head is at `8be29cacc79ecd50bd550f36e6ec900b21d527b5`, if that helps.

**Comment by Zirias** [comment]
I have a pretty good idea about the cause, it seems the string you get for `LC_ALL` for a "mixed" locale is platform-dependent and can't be used portably, so the fix should be to directly query the categories we need (`LC_CTYPE` for the character encoding and later, for translations, `LC_MESSAGES`). I can't reproduce the issue on any BSD system and my Debian VM currently refuses to work, so give me some time to fix that first to verify :)

**Comment by Zirias** [comment]
Some experimentation confirmed my guess. I'll commit a fix in a minute, please test it and reopen in case it doesn't fix your issue.

**Comment by ndegruchy** [comment]
Seems to have worked!

Thanks!
